### ISSUE TITLE
include rule on co-teaching?

### ISSUE THREAD

**Issue by raynamharris** [gvwilson/collaborative-lesson-development#1]
Maybe its beyond the scope, but I can't help but think that there should be a rule about co-teaching. 

One of the things that is really useful is observing other people teach the same materials. This could provide the foundation for the threaded discussions that are proposed in rule 9.

**Comment by gdevenyi** [comment]
Not quite sure what co-teaching is?

**Comment by raynamharris** [comment]
Teaching with a co-instructor. Only one of you is a the front of the class at a given time, but both are in the room at the same time.

**Comment by raynamharris** [comment]
I'm thinking this would fall under a more broad rule lesson study. There are many benefits of teaching with a partner:

- give each other constructive feedback
- evaluate the lessons and assessment results together
- take notes, comment on lessons in real-time while the other is teaching
- bring in multiple perspectives and ideas about the lessons
- ...

**Comment by gvwilson** [comment]
I think that lesson *delivery* is out of scope for this paper (though it would be a great topic for a second one).

**Comment by raynamharris** [comment]
Should there be a discussion of the teachers of the lessons? Does that fall under the discussion in the preamble or the rule about community or the rule about potential conflicts?
