### ISSUE TITLE
Assumptions for the preamble

### ISSUE THREAD

**Issue by k8hertweck** [gvwilson/collaborative-lesson-development#11]
What are we assuming about the audience for this paper? Here are a few basics to start:

- collaborative means geographically dispersed, diverse community of contributors
- lessons are under continuous development and repeated use (as opposed to created/taught once)

**Comment by raynamharris** [comment]
Do they have to be geographically dispersed and diverse communities? I think diversity is an important feature, but I wonder if that is a consequence of it being community driven rather than being an assumption. Also, does it have to be geographically dispersed or is that just one of the unique features that we are used to from the Software Carpentry community...

**Comment by k8hertweck** [comment]
I think this is why I'm labeling them as "assumptions," because then we don't have to assign value judgements or causation to them. The way I would frame it: dispersed, diverse collaborators are likely the trickiest type to manage, organize and motivate, and our rules are designed to facilitate lesson development in these communities. Perhaps it would help to specify a bit more what the community composition might include (which may represent particular challenges):

- geographically dispersed (e.g., global)
- diverse in terms of gender, culture, ethnicity, race
- many career stages (students through professionals)
- interdisciplinary (science through humanities)

**Comment by gvwilson** [comment]
Text added in b759dd4 - please have a look and hack?

**Comment by gvwilson** [comment]
@k8hertweck any feedback on the revised preamble?

**Comment by gdevenyi** [comment]
Looks okay to me

**Comment by k8hertweck** [comment]
This is great, thanks for organizing my thoughts. I'd be happy to personally work on this section when it comes time to write. Also, apologies for finals week drama distracting me from things like this!
