### ISSUE TITLE
#6 stands out as being extranenous

### ISSUE THREAD

**Issue by gdevenyi** [gvwilson/collaborative-lesson-development#12]
Compared to the rest of the rules, licence/code-of-couduct/governance seems a bit bureaucratic

**Comment by gdevenyi** [comment]
Thoughts?

**Comment by gvwilson** [comment]
I think it's part of enabling contribution - if the rules aren't clear, people won't.  Fold it into another rule?

**Comment by gvwilson** [comment]
@gdevenyi any thoughts on the revision for this?

**Comment by gdevenyi** [comment]
Much better +1
