### ISSUE TITLE
notes from April 24th discussion

### ISSUE THREAD

**Issue by raynamharris** [gvwilson/collaborative-lesson-development#13]
Here's a brief summary of today's meeting.  I'm not sure we will have enough hangouts to warrant a minutes folder, so I'll drop them here for now

### April 28 Google Hangout Discussion
Monday 19:00 Central Time /  Monday 20:00 Eastern / Tuesday 00:00 UTC.

### Attendees
Greg, Rayna, Kate, Damien , Gabriel

### Notes
- An academically digestible way to get credit for what we have done and getting credit for what we have done. 
- Best practice and good enough practices. Prioritize the top 10 and order them. 
- Let's lay down a bunch of things until we have more than 10. 
- Remember that you aren't building lessons you are building a community. 
- Without pruning and continual maintance, lessons go stale. 
- Level of continuity. 
- Preamble. Here is what we mean by collaborative development and provide the solution that this solves. 
- Target audience and goals. many audiences: anyone teaching anywhere 
- **Action item:** Rayna - will talk to a librarian about keywords so that our paper is discoverable
- the next paper could be about 10 simple rules article for making your research more discoverable
- **Action item:** Finish the paper in 3 months
- **Action item:** Everyone add as many other rules as issues so we can see them all. 
- Resource: Morgan and Gre's paper about making research software more robust: http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005412

**Comment by gvwilson** [comment]
Moved into README or addressed in more specific issues.
