### ISSUE TITLE
Remember that you aren't building lessons you are building a community

### ISSUE THREAD

**Issue by raynamharris** [gvwilson/collaborative-lesson-development#17]
Adding a rule mention by Greg's during the meeting

**Comment by raynamharris** [comment]
I'm thinking you need identify the glue that that holds the community together and provides a common goal. By identifying the audiences, you can work backwards to develop the lessons. Our mission and vision will help us decided what we do and do not teach. The community will help us develop and maintain high quality lessons.

**Comment by gvwilson** [comment]
@raynamharris now the second rule - what do you think?

**Comment by raynamharris** [comment]
Looks good!
