### ISSUE TITLE
Is #5 too complex to be a simple rule?

### ISSUE THREAD

**Issue by raynamharris** [gvwilson/collaborative-lesson-development#18]
Currently, # 5 is 'Encourage lots of little contributions'.  It contains 3 bullet points, with the 3rd stating that the rules 6-8 are about reducing social and technical barriers to contribution.

To me, calling out the hierarchy makes it more complex than simple. Can we restructure these so as to remove the hierarchy?

**Comment by gvwilson** [comment]
I agree that this rule is a long one, but the other papers we've done have also each had one or two rules that were much longer than others. Thoughts from others?

**Comment by gdevenyi** [comment]
I think all those points justifiably fall under this rule

**Comment by raynamharris** [comment]
Sounds good to me.
