### ISSUE TITLE
What problem are we trying to solve?

### ISSUE THREAD

**Issue by DamienIrving** [gvwilson/collaborative-lesson-development#19]
My take: 
Right now there are hundreds (if not thousands) of university lecturers teaching first year biology, third year computational mathematics, second year Indian film, and so on. Some of them might be using a common textbook written by a single author or two, but besides that they are essentially developing their course materials and learning from their mistakes in isolation. It is staggering to think (a) how many wheels are being re-invented in this process, and (b) how the progress of teaching in any one of these fields has been held back by the utter lack of community collaboration and sharing.

This problem obviously extends beyond just university teaching, but it is particularly curious that it should arise in tertiary education, given that the human research endeavour depends so critically on collaboration and sharing.

In the end, it was the software community's model of collaborative code development that would find it's way into tertiary education, in the form of lessons on basic lab skills for research computing...

**Comment by k8hertweck** [comment]
Wow, this is a great way to pitch the article and reach an even broader audience than those already involved in community lesson development. It also allows a nice segue into my other preamble topic #11 ,  about what we mean by community development (or who's in the community).

**Comment by gvwilson** [comment]
Added to preamble - thanks!
