### ISSUE TITLE
Expand the rule on instructional design?

### ISSUE THREAD

**Issue by DamienIrving** [gvwilson/collaborative-lesson-development#20]
Is the focus of draft rule 3 too narrow?

3. Design the lesson backward, but describe it forward.
- Quick review of reverse instructional design.
- But describe forward (since that's comprehension order).

**Comment by DamienIrving** [comment]
I think instructor training was key to the success of the Software Carpentry collaborative lesson development. Before contributing to the lessons, contributors were educated on relevant teaching best practices as well as the history and rationale behind the current set of lessons (as well as the practicalities of making a contribution via GitHub). Having everyone start from this common baseline level of knowledge helped enormously (IMHO). 

Perhaps this rule would be better phrased as follows?

3. Educate new contributors on the rationale behind the current lessons
* Best practices that the community is trying to implement (e.g. reverse instructional design)  
* History behind major design and content decisions

**Comment by gvwilson** [comment]
Good point - folded in.
