### ISSUE TITLE
rule on real-time and long-term analysis of summative assessment

### ISSUE THREAD

**Issue by raynamharris** [gvwilson/collaborative-lesson-development#21]
I think the Software Carpentry lessons really benefit from using multiple types of assessment before, during, and after workshops. 

Having sticky notes for real-time assessment allows the instructor to make decisions while teaching the lesson. Over the long-term, surveys and discussions gives us a birds-eye view of how the lessons work as a whole, including what is working really well and what needs to be fixed.

**Comment by gvwilson** [comment]
Things like sticky notes are about *delivering* lessons rather than *constructing* them - I think there's lots of room for a second 10 Rules paper on the former, but we should focus this paper on the latter.

**Comment by raynamharris** [comment]
I agree that sticky notes are about delivery lessons rather than constructing them. However, we can and do use sticky notes to assess quality and efficacy of our lessons. This form of feedback can be and is incorporated into the lesson maintenance process. 

Is it within the scope to discuss rules for lesson maintenance?

**Comment by gvwilson** [comment]
Added #28 to incorporate this - @ianmilligan1 and @raynamharris can you please have a look?
