### ISSUE TITLE
Three main audiences for lessons

### ISSUE THREAD

**Issue by k8hertweck** [gvwilson/collaborative-lesson-development#22]
There are three main audiences for lessons that are published for free online:

1. instructors who will be teaching workshops from the materials
2. students from said workshops who will reference the materials afterwards
3. folks not attending workshops but who use the materials to learn on their own

Balancing the needs of these audiences represent different choices in what information is available (level of detail) and where it can be found (main lesson pages vs other links), as well as the overall design/layout of the lesson. 

It's worth noting that the SWC lessons, for example, are designed largely by instructors with a layout conducive to teaching, but are very often used by folks from 2 and 3.

**Comment by gvwilson** [comment]
Folded into `notes.md`
