### ISSUE TITLE
Figure ideas

### ISSUE THREAD

**Issue by raynamharris** [gvwilson/collaborative-lesson-development#23]
Have y'all ever seen [this animation](https://www.youtube.com/watch?v=2zMgY8Dx9co) about why preprint servers are awesome? This video gives me inspiration for two figures for the preamble.

1. A side-by-side comparison of non-collaborative and collaborative lesson development
2. A graphical summary of the advantages of collaborative  lesson development

I haven't sketched it for lesson development yet, but here are two screen shots that do points 1 and 2 for **preprints**.
![screen shot 2017-04-27 at 2 36 14 pm](https://cloud.githubusercontent.com/assets/7544197/25501271/ca09769a-2b57-11e7-96d3-f1754e1264f5.png)
![screen shot 2017-04-27 at 2 37 34 pm](https://cloud.githubusercontent.com/assets/7544197/25501272/ca166ada-2b57-11e7-89a9-6d7ab8b24fae.png)

**Comment by k8hertweck** [comment]
This is interesting! The 10 simple rules papers don't always have figures, but I like the idea of a graphical summary of advantages. I'm having trouble envisioning the first, but would love to see what you're envisioning!

**Comment by raynamharris** [comment]
I was thinking that we could compare the workflow for collaborative publishing versus traditional publishing like this. The main difference highlighted here are 1) the number of middle steps between lesson creators and students and 2) the presence or absence of direct lines of feedback via assessment 
![img_2789](https://cloud.githubusercontent.com/assets/7544197/25596640/d3b4ae04-2e8f-11e7-89f1-98de6daca820.JPG)
from leaners to lesson creators.

**Comment by gdevenyi** [comment]
Totally love the idea of comparing traditional publishing to this.

**Comment by raynamharris** [comment]
What do y'all think about a text-based graphical abstract. To created this image, I shorted the description of each rule to ~30 characters. Do these concise wordings convey the meaning of the rule appropriately?
![2017-05-17-rules-01](https://cloud.githubusercontent.com/assets/7544197/26184959/7771cb66-3b4d-11e7-8079-2c47796da2ed.png)

**Comment by raynamharris** [comment]
And here's a first draft of what an actual graphical abstract could look like.  I got stuck on a few rules, but maybe you get the gist

![2017-05-17-rules-02](https://cloud.githubusercontent.com/assets/7544197/26187072/ecf52000-3b5b-11e7-963d-a998d07c1f91.png)

**Comment by gvwilson** [comment]
:+1:

**Comment by ianmilligan1** [comment]
This is fantastic!

**Comment by gdevenyi** [comment]
Graphical abstract looks nice!

Are we still planning to include a figure which compares the publishing processes, as the draft above?

**Comment by raynamharris** [comment]
I think an image comparing the two processes would be very useful. However, I'm not sure I actually know that are the salient points. It would help to have it written our first and then use that as a template for making the figure.

**Comment by raynamharris** [comment]
This is an updated graphical abstract of the rules, nearly in the exact same order as the rules. 

I still don't know what images fit with rule 10.

![2017-05-17-rules-02](https://cloud.githubusercontent.com/assets/7544197/26650678/cf43059a-460f-11e7-87a4-c42fa62ee73e.png)
