### ISSUE TITLE
10) You can't make everyone happy

### ISSUE THREAD

**Issue by k8hertweck** [gvwilson/collaborative-lesson-development#24]
I feel very strongly that we have to admit this somewhere in the article. The basic premise is that you will never get a community of people to agree on everything all of the time, and you have to be ready to manage differing opinions. I'd appreciate some input about when it is to mention this, though. What's strategically better, to mention it up front (get it out of the way and treat it as a caveat), or at the end (after you've painted a rosy picture and want to crush everyone's dreams)?

**Comment by gvwilson** [comment]
I've added something about when to present alternatives and when to fork - please have a look and hack on it?

**Comment by gvwilson** [comment]
@k8hertweck can you please have a look at the final rule and let us know what you think?
