### ISSUE TITLE
Flesh out description of publication process

### ISSUE THREAD

**Issue by gvwilson** [gvwilson/collaborative-lesson-development#29]
Hi Remi,
Can you please look at the rule that says "publish periodically" and add half a dozen bullet points about the mechanics of doing this?
Thanks,
Greg

**Comment by twitwi** [comment]
Sure.
Preferably directly on master or in a branch for review?

**Comment by gvwilson** [comment]
Ping @twitwi

**Comment by twitwi** [comment]
I started out and got busy... progress will show up in https://github.com/gvwilson/collaborative-lesson-development/tree/wip-rule-7
I'm closing in favor of https://github.com/gvwilson/collaborative-lesson-development/issues/37
