### ISSUE TITLE
examples of collaborative lesson development

### ISSUE THREAD

**Issue by DamienIrving** [gvwilson/collaborative-lesson-development#3]
I figured it would be useful to start an issue to collect examples of collaborative lesson development. It might be worth mentioning/dissecting some examples in the paper (perhaps good and bad examples), otherwise it's all a bit abstract.

The most obvious examples that come to mind are [Software Carpentry](https://software-carpentry.org/lessons/) and [Data Carpentry](http://www.datacarpentry.org/lessons/).

Mozilla Science Lab also have a [study group lesson bank](https://github.com/mozillascience/studyGroupLessons), however as far as I'm aware not much collaboration goes on to further develop those lessons once they're dumped in the repo.

What else is out there?

**Comment by raynamharris** [comment]
I like this idea a lot. This could be provided in a callout box or in the main text. I'll see if I can think of some non-Carpentry examples

**Comment by gvwilson** [comment]
I don't know of examples - almost all OER (Open Educational Resources) follow the "write once, dump, nobody updates" model.  I think we should mention Wikipedia and open source software as examples of what we're striving for.

...which makes me think: are there intro tutorials for specific software packages that are updated in situ as people update the software?

**Comment by twitwi** [comment]
These are not strictly lessons, but maybe https://www.wikibooks.org/ is worth mentioning.

**Comment by DamienIrving** [comment]
During the skype meeting @gvwilson mentioned that the [Programming Historian](http://programminghistorian.org/) uses a slightly different model than Software Carpentry.

**Comment by ianmilligan1** [comment]
I'm part of the Programming Historian team – hi everybody! The model there is more from the traditional academic world, where (a) authors propose a lesson; (b) authors are assigned an editor who works with them; (c) [a submission ticket is opened in a GitHub repo](https://github.com/programminghistorian/ph-submissions/issues/60), with two invited 'peer reviewers' as well as community comments; (d) the lesson is posted. We haven't quite figured out ongoing maintenance, however, as the author-ownership model doesn't always lend itself well to mass community edits.

**Comment by raynamharris** [comment]
Cool. It seems like [the Programming Historian](http://programminghistorian.org) really nice system for submission and peer review.

**Comment by k8hertweck** [comment]
Hi @ianmilligan1, welcome and glad to have you on board! Thanks for clarifying how your system works. Even if you aren't already implementing a maintenance procedure, it's worth noting that (by virtue of GitHub hosting), it's actually possible in a more explicit way than other types of publication (e.g., an author or someone else has a mechanism through which to submit a PR that would allow updating links, etc).

**Comment by DamienIrving** [comment]
@gvwilson @ianmilligan1 Do we need to come up with some text for the preamble that summarisies this thread? At the moment programs like Software Carpentry and Programming Historian are mentioned randomly throughout notes.md without any real introduction.

I think this would help address the "FIXME: fill in introduction" in paper.tex...

That text could mention that we are striving for a wikipedia / open source software model, by which we mean lesson materials are:
1. Open and easily accessible
2. Continually maintained/refined/improved by a large community of contributors

To the author's knowledge, the Carpentries are the only real-world example that satisfy both these criteria. The Programming Historian and other open educational resources like MOOCs satisfy criteria 1 but not 2 (i.e. "write once, dump, nobody updates"). They might experience a kind of iterative development where the lessons are periodically updated by a small author group (e.g. this happens when a new edition of an academic textbook is released), but this is not the same as regular, small releases/updates from a large community of contributors. We think the latter is preferable because (a) the lessons are always up-to-date with the latest information, and (b) the lessons don't die when a key author moves on.

**Comment by ianmilligan1** [comment]
I love this! I am working on this right now, maybe I can try incorporating it into an intro to SW and PH more generally?
