### ISSUE TITLE
4) Build lessons, not courses

### ISSUE THREAD

**Issue by gvwilson** [gvwilson/collaborative-lesson-development#34]

**Comment by DamienIrving** [comment]
Every instructor's needs are different, so build small chunks that can be re-purposed in many ways. A university lecturer in meteorology, for instance, might construct a course by bringing together lessons on differential equations, fluid mechanics and absorption spectroscopy. This task is greatly simplified if existing courses on mathematics, physics and chemistry consist of numerous small, discrete lessons, as opposed to a few large, monolithic lessons.

**Comment by gdevenyi** [comment]
Addition:
Individual lesson topics hinge on the learners having the proper prerequisite background, so this rule further emphasizes the importance of rule 1.
