### ISSUE TITLE
untapped community developed laboratory lesson materials

### ISSUE THREAD

**Issue by raynamharris** [gvwilson/collaborative-lesson-development#53]
For the next two two months, me and about 80 other faculty members from around the world will be preparing lessons materials and exercises for the [Neural Systems & Behavior Course](http://www.mbl.edu/nsb/) at the [Marine Biological Labs](http://www.mbl.edu).

I don't have the literature search to prove my point, but I don't think that any of the 30 years of teaching materials generated by this course have ever been formally published. Last year, I archived the material I developed in Zenodo (inspired by Greg of course), but I think I'm the only one. 

I can't help but wonder how many gems of community developed teaching materials (used a places like Cold Spring Harbour and the Marine Biological Lab that do intense research bootcamps) are out there stored on personal hard drives without DOIs or anything else that would provide a citable and sharable research and teaching output.

**Comment by raynamharris** [comment]
[http://www.mbl.edu](url)

**Comment by gvwilson** [comment]
"Every question you have that other people might want answered should turn into a paper."
- me, to grad students, many times

So: can you survey the 80 faculty you mentioned and ask them where their materials are stored, what format they're in, how many people have contributed to them, what their plans for maintenance are ("who will use this when I'm gone?"), and whether they've ever been published in citable form?  Tell 'em what we're working on, and if they've heard of the Carpentries (I'm guessing many will), there's a good chance they'll reply to a short survey and we can include the data in this paper.

**Comment by raynamharris** [comment]
What's the turn around time I would need to create, distribute, analyze, and interpret the survey results in time to get it into the paper? The course starts in 1 week, so the timing is good to encourage them to reply.

**Comment by raynamharris** [comment]
I created a short survey. I'm not really happy with it though. Questions are hard to design well. I'm not sure they fit the objective of trying to figure out if and where people are publishing their lesson materials.

https://utexas.qualtrics.com/jfe/form/SV_7R6lXcwHMGIh6VT

**Comment by gvwilson** [comment]
Looks fine to me - only thing I'd change is to add something on the 
welcome page saying that we're interested in comparing Software 
Carpentry's approach with that used by other people. Ship it.

**Comment by raynamharris** [comment]
Great suggestion. Thanks!
