### ISSUE TITLE
Discuss discoverability as well as licensing

### ISSUE THREAD

**Issue by gvwilson** [gvwilson/collaborative-lesson-development#64]

**Comment by ianmilligan1** [comment]
For here, do we mean highlighting ways that a lesson can be discovered? I could talk about our work trying to get Programming Historian into library databases (ISSNs?). Or something else?

**Comment by raynamharris** [comment]
I think this is really important. I really like how the Zenodo citation for published lessons allows me to cite them in the literature and look at alternative metics.
