### ISSUE TITLE
Provide suggestions for properly-licenced support material?

### ISSUE THREAD

**Issue by gdevenyi** [gvwilson/collaborative-lesson-development#8]
Should we point at material which is properly licenced for inclusion?

I'm thinking example data and images.

**Comment by gvwilson** [comment]
Do you mean "tell people to check licenses before including material" or "point them at repositories of reusable material"?  If the first, I think it's out of scope (it's about open rather than collaborative, which are orthogonal).  If the second, I think we could do an entire paper...

**Comment by gdevenyi** [comment]
I was thinking the second, to expand on the idea of "don't redo stuff"

I agree a whole paper would be better, but maybe a small list?
