### ISSUE TITLE
10) Document common conficts

### ISSUE THREAD

**Issue by gdevenyi** [gvwilson/collaborative-lesson-development#9]
Certain topics have common disagreements about how to teach/explain things

Suggest documenting that somewhere?

**Comment by raynamharris** [comment]
I like this! I wonder if this similar enough to to providing flexibility (e.g. exercise option A and B) or if highlighting conflicts and providing alternatives are two distinct topics.

**Comment by raynamharris** [comment]
I keep coming back to this conflicts issue.

I'm wondering if there should be a rule about balancing flexibility with stability. They should be flexible to account for teacher/learner/classroom differences but should be stable enough that there is a brand and core set of materials.

**Comment by gvwilson** [comment]
Discussed in b759dd4 - please have a look and hack away?

**Comment by gvwilson** [comment]
@gdevenyi @raynamharris any feedback on the revised wording?

**Comment by raynamharris** [comment]
I think this is going to be a really important rule. 

A few things:
1.  I'm not sure what "Cf. choral explanations." means.
2.  I think it could be good to point to some examples of forked lessons.  Maybe [R gapminder](http://swcarpentry.github.io/r-novice-gapminder) and [R inflammation](http://swcarpentry.github.io/r-novice-inflammation) or [Python gapminder](http://swcarpentry.github.io/python-novice-gapminder/) and [Python inflammation](http://swcarpentry.github.io/python-novice-inflammation/).

**Comment by gvwilson** [comment]
Choral explanations:
*   https://hapgood.us/2016/05/13/choral-explanations/
*   https://hapgood.us/2016/07/12/choral-explanations-and-oer-a-summary-of-thinking-to-date/

**Comment by raynamharris** [comment]
Thanks @gvwilson. The first one gives a pretty clear and concise description.

**Comment by gdevenyi** [comment]
I like the additions about disagreements, but I wonder if there should still be a suggestion to at least note things that people often disagree about on a given lesson and why it is the way it is (as of the current time).

I'll see if I can make that into a coherent suggestion in the list.
